<h1 style="color:red">Handling Text and Catagorical Attributes -  </h1>

<h2 style="color:limegreen">Label Encoding -  </h2>


- Label encoding is to assign posiitve numbers for all the catagorical variables

<img src="images\\EDA2_D1.png" alt='src' width='200px' style="margin-left:100px">

- In this dataset, country is catagorical variable, the country names will be replaced by numbers 0,1,2 when we apply lebel encoding
- If the __target column is catagoric__, we can use __LabelEncoder__
- If the __feature column is catagoric__, we can use __OneHotEncoder__

<h2 style="color:limegreen">One Hot Encoding -  </h2>

- Catagorical variables have to be converted into numerical using method called One-hot encoding
- It is done by using __pd.get_dummies(df)__

<img src="images\\EDA2_D2.png" alt='src' width='500px' border='1px'>

<h1 style="color:red">Isolation Forest for Outlier Detection -</h1>

- Lot of ML algorithms suffer in terms of their performance when outliers are not treated
- In order to avoid this problem-
  - drop them from the sample
  - can the values at some reasonable point
  - or transfer the data
 
__Isolation Forest algorithm identifies the outliers in multidimensional space__

1. Isolation forest is built on decision trees

2. In these trees, partitions are created by first randomly selecting a feature and then selecting a random split value
    between the min and max of the selected feature

3. Generally, outliers are less in number than normal observations and are different from them in terms of values

4. They will be placed far away from the rest of the data points in the feature space

5. That is why by using such random partitioning they should be identified closer to the root of the tree, with fewer splits necessary

### Steps

<div>

<img src="images\\EDA2_Step1.png" alt='src' width='45%' style="border:1px solid black;height:300px">
<img src="images\\EDA2_Step2.png" alt='src' width='45%' style="border:1px solid black;height:300px">

</div>
<div>
<img src="images\\EDA2_Step3.png" alt='src' width='45%' style="border:1px solid black;height:300px">
<img src="images\\EDA2_Step4.png" alt='src' width='45%' style="border:1px solid black;height:300px">
    
</div>

<h1 style="color:red">Correlation Using Predictive Power Score (PPS) -</h1>

__What will be coefficient of correlation for the following associations??__

<img src="images\\EDA2_D3.png" alt='src' width='700px' style="margin-left:100px">

- If the relationship is linear between the params then we can use correlation coefficient to find the strength of assocition
- What if relationship is non-linera, gaussian or unknown relationship like imgs above, how do we find the association?
- What if we want to detect __relationship between cities and zip codes ?__
- The expectation is that, irrespective of the relationship between the params we would like to know the relationship
- And the __score should be 0 if there is no relationship and the score should be 1 if there is a perfect relationship__
- Also score __should be able to handle categoric and numeric columns__

<h2 style="color:limegreen">Predictive Power Score (PPS) -</h2>

- PPS is an asymmetric, data-type-agnostic score that can detect linear or non-linear relationships between 2 columns
- __Score ranges from 0 (no predicive power) to 1 (perfect predictive power)__
- It can be used as an __alternative to the correlation matrix__

Let's say we have 2 columns and want to calculate the PPS of A predicting B. In this case, we treat B as our target 
variable and A as our feature.

- We can now calculate a __cross-validated Decision Tree__ and __calculate suitable evaluation metric__
- When the target is numeric we can use a __Decision Tree Regressor__ and calculate the __Mean Absolute Error(MAE__)
- When the target is catagorical, we can use __Decision Trre Classifier__ and calculate the __weighted F1__

<h3 style="color:blue">Example: Zip Codes and City Names</h3>

- Calculate PPS of zip code to city
- Weighted __F1 score__ will be used because __city is categoric__
- Let's say cross-validated __Decision Tree Classifier__ achieves a score of __0.95 F1__
- Then calculate baseline score via always predicting the most common city and achieve a score of __0.1 F1__
- Normalize the score, you will get final PPS of 0.94 after applying following normalization formula __(0.95-0.1)/(1-0.1)__
- As we can see, a PPS score of 0.94 is rather high, so __zip codes seems to have good predictive power towards city__
- However if we calculate PPS in opposite direction, we might have PPS of close to 0

<h3 style="color:blue">Comparing PPS to Correlation</h3>

<img src="images\\EDA2_D4.png" alt='src' width='600px' border="1px">

In [16]:
# For Regreesion and Classification

<div style="display:flex">

<img src="images\\EDA2_D5.png" alt='src' width='45%' border="1px">
<img src="images\\EDA2_D6.png" alt='src' width='45%' border="1px">
    
</div>

# Example Code

### Label Encoder

In [20]:
import pandas as pd

In [21]:
# importing dataset

df = pd.read_csv("Datasets\\iris1.csv")
df.head()

   Unnamed: 0  Sepal.Length  Sepal.Width  Petal.Length  Petal.Width Species
0           1           5.1          3.5           1.4          0.2  setosa
1           2           4.9          3.0           1.4          0.2  setosa
2           3           4.7          3.2           1.3          0.2  setosa
3           4           4.6          3.1           1.5          0.2  setosa
4           5           5.0          3.6           1.4          0.2  setosa

In [22]:
df1 = df.copy()

In [23]:
# importing required package

from sklearn.preprocessing import LabelEncoder

In [24]:
le = LabelEncoder()  # instance

# encoding last column
df1.iloc[:,-1] = le.fit_transform(df1.iloc[:,-1])

C:\Users\Yash\AppData\Local\Temp\ipykernel_4128\2949059360.py:4: DeprecationWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  df1.iloc[:,-1] = le.fit_transform(df1.iloc[:,-1])

In [25]:
df1    # species columns devided into 3 labels

     Unnamed: 0  Sepal.Length  Sepal.Width  Petal.Length  Petal.Width  Species
0             1           5.1          3.5           1.4          0.2        0
1             2           4.9          3.0           1.4          0.2        0
2             3           4.7          3.2           1.3          0.2        0
3             4           4.6          3.1           1.5          0.2        0
4             5           5.0          3.6           1.4          0.2        0
..          ...           ...          ...           ...          ...      ...
145         146           6.7          3.0           5.2          2.3        2
146         147           6.3          2.5           5.0          1.9        2
147         148           6.5          3.0           5.2          2.0        2
148         149           6.2          3.4           5.4          2.3        2
149         150           5.9          3.0           5.1          1.8        2

[150 rows x 6 columns]

### One Hot Encoder

In [27]:
df2 = df.copy()

In [28]:
df2

,Unnamed: 0,Sepal.Length,Sepal.Width,Petal.Length,Petal.Width,Species
0,1,5.1,3.5,1.4,0.2,setosa
1,2,4.9,3.0,1.4,0.2,setosa
2,3,4.7,3.2,1.3,0.2,setosa
3,4,4.6,3.1,1.5,0.2,setosa
4,5,5.0,3.6,1.4,0.2,setosa
...,...,...,...,...,...,...
145,146,6.7,3.0,5.2,2.3,virginica
146,147,6.3,2.5,5.0,1.9,virginica
147,148,6.5,3.0,5.2,2.0,virginica
148,149,6.2,3.4,5.4,2.3,virginica
149,150,5.9,3.0,5.1,1.8,virginica

In [29]:
# importinf required package

from sklearn.preprocessing import OneHotEncoder

In [30]:
# instance

OHE = OneHotEncoder()

In [31]:
# when applied fit_transform it will not does changes in place, rather create a Compressed Sparse Row format response

# We have to convert it to array , then convert to dataframe and finally concatinate with original df

encoded_df = pd.DataFrame(OHE.fit_transform(df2[['Species']]).toarray())

In [32]:
encoded_df

       0    1    2
0    1.0  0.0  0.0
1    1.0  0.0  0.0
2    1.0  0.0  0.0
3    1.0  0.0  0.0
4    1.0  0.0  0.0
..   ...  ...  ...
145  0.0  0.0  1.0
146  0.0  0.0  1.0
147  0.0  0.0  1.0
148  0.0  0.0  1.0
149  0.0  0.0  1.0

[150 rows x 3 columns]

In [33]:
data_final = df2.iloc[:,1:5].join(encoded_df)
data_final

     Sepal.Length  Sepal.Width  Petal.Length  Petal.Width    0    1    2
0             5.1          3.5           1.4          0.2  1.0  0.0  0.0
1             4.9          3.0           1.4          0.2  1.0  0.0  0.0
2             4.7          3.2           1.3          0.2  1.0  0.0  0.0
3             4.6          3.1           1.5          0.2  1.0  0.0  0.0
4             5.0          3.6           1.4          0.2  1.0  0.0  0.0
..            ...          ...           ...          ...  ...  ...  ...
145           6.7          3.0           5.2          2.3  0.0  0.0  1.0
146           6.3          2.5           5.0          1.9  0.0  0.0  1.0
147           6.5          3.0           5.2          2.0  0.0  0.0  1.0
148           6.2          3.4           5.4          2.3  0.0  0.0  1.0
149           5.9          3.0           5.1          1.8  0.0  0.0  1.0

[150 rows x 7 columns]

In [34]:
# using pandas this task is very easy

In [35]:
df3 = df.copy()
df3

,Unnamed: 0,Sepal.Length,Sepal.Width,Petal.Length,Petal.Width,Species
0,1,5.1,3.5,1.4,0.2,setosa
1,2,4.9,3.0,1.4,0.2,setosa
2,3,4.7,3.2,1.3,0.2,setosa
3,4,4.6,3.1,1.5,0.2,setosa
4,5,5.0,3.6,1.4,0.2,setosa
...,...,...,...,...,...,...
145,146,6.7,3.0,5.2,2.3,virginica
146,147,6.3,2.5,5.0,1.9,virginica
147,148,6.5,3.0,5.2,2.0,virginica
148,149,6.2,3.4,5.4,2.3,virginica
149,150,5.9,3.0,5.1,1.8,virginica

In [36]:
pd.get_dummies(df,columns=['Species'])   # or pd.get_dummies(df)

,Unnamed: 0,Sepal.Length,Sepal.Width,Petal.Length,Petal.Width,Species_setosa,Species_versicolor,Species_virginica
0,1,5.1,3.5,1.4,0.2,1,0,0
1,2,4.9,3.0,1.4,0.2,1,0,0
2,3,4.7,3.2,1.3,0.2,1,0,0
3,4,4.6,3.1,1.5,0.2,1,0,0
4,5,5.0,3.6,1.4,0.2,1,0,0
...,...,...,...,...,...,...,...,...
145,146,6.7,3.0,5.2,2.3,0,0,1
146,147,6.3,2.5,5.0,1.9,0,0,1
147,148,6.5,3.0,5.2,2.0,0,0,1
148,149,6.2,3.4,5.4,2.3,0,0,1
149,150,5.9,3.0,5.1,1.8,0,0,1

## Isloation Forest

In [38]:
# Isolation Forest example - useful for anomaly detection along with outliers
from sklearn.ensemble import IsolationForest

In [39]:
# SAmple example before iris set


df=pd.DataFrame({
      'Marks':[50,80,82,95,800],
      'Time':[1,2,3,1.5,60]
})
df

   Marks  Time
0     50   1.0
1     80   2.0
2     82   3.0
3     95   1.5
4    800  60.0

In [40]:
# clearly datapoint 4 is outlier

In [41]:
#iso=IsolationForest(random_state=10)# expecting 10 % outlier in dataset

iso = IsolationForest(random_state=42,contamination=0.1)
out = iso.fit_predict(df)

In [42]:
out    # last value is an outlier

array([ 1,  1,  1,  1, -1])

In [43]:
df['Score'] = out
df

   Marks  Time  Score
0     50   1.0      1
1     80   2.0      1
2     82   3.0      1
3     95   1.5      1
4    800  60.0     -1

In [44]:
data = pd.get_dummies(df3)
data.drop(columns=data.columns[0],inplace=True)

In [45]:
data

,Sepal.Length,Sepal.Width,Petal.Length,Petal.Width,Species_setosa,Species_versicolor,Species_virginica
0,5.1,3.5,1.4,0.2,1,0,0
1,4.9,3.0,1.4,0.2,1,0,0
2,4.7,3.2,1.3,0.2,1,0,0
3,4.6,3.1,1.5,0.2,1,0,0
4,5.0,3.6,1.4,0.2,1,0,0
...,...,...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,0,0,1
146,6.3,2.5,5.0,1.9,0,0,1
147,6.5,3.0,5.2,2.0,0,0,1
148,6.2,3.4,5.4,2.3,0,0,1
149,5.9,3.0,5.1,1.8,0,0,1

In [46]:
# training model 

clf = IsolationForest(random_state=10,contamination=0.01)
# contamination: how much percentage of outliers you are expecting in dataset
# eg. in health care domain it will be very low (1% or less) 0.01 or 0.001

clf.fit(data)

IsolationForest(contamination=0.01, random_state=10)

In [47]:
preds = clf.predict(data)

In [48]:
preds

array([ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1, -1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1, -1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1])

In [49]:
#there are couple of outliers detected by -1

In [50]:
data.shape

(150, 7)

In [51]:
# Let's add additional outlier row intensionally

data.loc[150]=[20,40,30,50,1,0,0]
data

,Sepal.Length,Sepal.Width,Petal.Length,Petal.Width,Species_setosa,Species_versicolor,Species_virginica
0,5.1,3.5,1.4,0.2,1,0,0
1,4.9,3.0,1.4,0.2,1,0,0
2,4.7,3.2,1.3,0.2,1,0,0
3,4.6,3.1,1.5,0.2,1,0,0
4,5.0,3.6,1.4,0.2,1,0,0
...,...,...,...,...,...,...,...
146,6.3,2.5,5.0,1.9,0,0,1
147,6.5,3.0,5.2,2.0,0,0,1
148,6.2,3.4,5.4,2.3,0,0,1
149,5.9,3.0,5.1,1.8,0,0,1
150,20.0,40.0,30.0,50.0,1,0,0

In [52]:
# What do u think, will there be 3 outliers?

In [53]:
preds1 = clf.fit_predict(data)
preds1

array([ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1, -1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1, -1])

In [54]:
# Last one is outlier, but 1 of the previously identified is no more outlier now

In [55]:
data['anomaly'] = preds1

In [56]:
data

,Sepal.Length,Sepal.Width,Petal.Length,Petal.Width,Species_setosa,Species_versicolor,Species_virginica,anomaly
0,5.1,3.5,1.4,0.2,1,0,0,1
1,4.9,3.0,1.4,0.2,1,0,0,1
2,4.7,3.2,1.3,0.2,1,0,0,1
3,4.6,3.1,1.5,0.2,1,0,0,1
4,5.0,3.6,1.4,0.2,1,0,0,1
...,...,...,...,...,...,...,...,...
146,6.3,2.5,5.0,1.9,0,0,1,1
147,6.5,3.0,5.2,2.0,0,0,1,1
148,6.2,3.4,5.4,2.3,0,0,1,1
149,5.9,3.0,5.1,1.8,0,0,1,1
150,20.0,40.0,30.0,50.0,1,0,0,-1

In [57]:
data[data.anomaly==-1]

,Sepal.Length,Sepal.Width,Petal.Length,Petal.Width,Species_setosa,Species_versicolor,Species_virginica,anomaly
106,4.9,2.5,4.5,1.7,0,0,1,-1
150,20.0,40.0,30.0,50.0,1,0,0,-1

## PPS Score

In [59]:
# !pip install ppscore

In [60]:
# importing required package
            
import ppscore as pps

In [61]:
df3.drop(columns=df3.columns[0],inplace=True)
df3

     Sepal.Length  Sepal.Width  Petal.Length  Petal.Width    Species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [62]:
# Syntax: pps.score(df, "feature_column", "target_column")
pps.score(df3, "Sepal.Length", "Petal.Length") # ppscore:0.55 so ok kind of score

{'x': 'Sepal.Length',
 'y': 'Petal.Length',
 'ppscore': 0.550422595049248,
 'case': 'regression',
 'is_valid_score': True,
 'metric': 'mean absolute error',
 'baseline_score': 1.4886666666666668,
 'model_score': 0.6692708968366863,
 'model': DecisionTreeRegressor()}

In [63]:
# whole PPS matrix

pps.matrix(df3)

,x,y,ppscore,case,is_valid_score,metric,baseline_score,model_score,model
0,Sepal.Length,Sepal.Length,1.000000,predict_itself,True,None,0.000000,1.000000,None
1,Sepal.Length,Sepal.Width,0.000000,regression,True,mean absolute error,0.330667,0.364704,DecisionTreeRegressor()
2,Sepal.Length,Petal.Length,0.550423,regression,True,mean absolute error,1.488667,0.669271,DecisionTreeRegressor()
3,Sepal.Length,Petal.Width,0.431739,regression,True,mean absolute error,0.644667,0.366339,DecisionTreeRegressor()
4,Sepal.Length,Species,0.471649,classification,True,weighted F1,0.353333,0.658333,DecisionTreeClassifier()
5,Sepal.Width,Sepal.Length,0.006966,regression,True,mean absolute error,0.684667,0.679897,DecisionTreeRegressor()
6,Sepal.Width,Sepal.Width,1.000000,predict_itself,True,None,0.000000,1.000000,None
7,Sepal.Width,Petal.Length,0.172375,regression,True,mean absolute error,1.488667,1.232058,DecisionTreeRegressor()
8,Sepal.Width,Petal.Width,0.132858,regression,True,mean absolute error,0.644667,0.559017,DecisionTreeRegressor()
9,Sepal.Width,Species,0.156915,classification,True,weighted F1,0.353333,0.454805,DecisionTreeClassifier()
10,Petal.Length,Sepal.Length,0.525617,regression,True,mean absolute error,0.684667,0.324794,DecisionTreeRegressor()
11,Petal.Length,Sepal.Width,0.052136,regression,True,mean absolute error,0.330667,0.313427,DecisionTreeRegressor()
12,Petal.Length,Petal.Length,1.000000,predict_itself,True,None,0.000000,1.000000,None
13,Petal.Length,Petal.Width,0.744945,regression,True,mean absolute error,0.644667,0.164425,DecisionTreeRegressor()
14,Petal.Length,Species,0.884812,classification,True,weighted F1,0.353333,0.925512,DecisionTreeClassifier()
15,Petal.Width,Sepal.Length,0.383911,regression,True,mean absolute error,0.684667,0.421816,DecisionTreeRegressor()
16,Petal.Width,Sepal.Width,0.254616,regression,True,mean absolute error,0.330667,0.246474,DecisionTreeRegressor()
17,Petal.Width,Petal.Length,0.798274,regression,True,mean absolute error,1.488667,0.300302,DecisionTreeRegressor()
18,Petal.Width,Petal.Width,1.000000,predict_itself,True,None,0.000000,1.000000,None
19,Petal.Width,Species,0.927652,classification,True,weighted F1,0.353333,0.953215,DecisionTreeClassifier()
20,Species,Sepal.Length,0.409634,regression,True,mean absolute error,0.684667,0.404204,DecisionTreeRegressor()
21,Species,Sepal.Width,0.194307,regression,True,mean absolute error,0.330667,0.266416,DecisionTreeRegressor()
22,Species,Petal.Length,0.785393,regression,True,mean absolute error,1.488667,0.319479,DecisionTreeRegressor()
23,Species,Petal.Width,0.755749,regression,True,mean absolute error,0.644667,0.157460,DecisionTreeRegressor()
24,Species,Species,1.000000,predict_itself,True,None,0.000000,1.000000,None

In [111]:
df=pd.DataFrame(pps.matrix(df3))
df[df.case!='predict_itself'].iloc[:,[0,1,2,3,5,8]].sort_values('ppscore',ascending=False)
# PPScore is highest in petal.width and species i.e. 0.927652 i.e. petal width is very good feature in predicting species

,x,y,ppscore,case,metric,model
19,Petal.Width,Species,0.927652,classification,weighted F1,DecisionTreeClassifier()
14,Petal.Length,Species,0.884812,classification,weighted F1,DecisionTreeClassifier()
17,Petal.Width,Petal.Length,0.798274,regression,mean absolute error,DecisionTreeRegressor()
22,Species,Petal.Length,0.785393,regression,mean absolute error,DecisionTreeRegressor()
23,Species,Petal.Width,0.755749,regression,mean absolute error,DecisionTreeRegressor()
13,Petal.Length,Petal.Width,0.744945,regression,mean absolute error,DecisionTreeRegressor()
2,Sepal.Length,Petal.Length,0.550423,regression,mean absolute error,DecisionTreeRegressor()
10,Petal.Length,Sepal.Length,0.525617,regression,mean absolute error,DecisionTreeRegressor()
4,Sepal.Length,Species,0.471649,classification,weighted F1,DecisionTreeClassifier()
3,Sepal.Length,Petal.Width,0.431739,regression,mean absolute error,DecisionTreeRegressor()
20,Species,Sepal.Length,0.409634,regression,mean absolute error,DecisionTreeRegressor()
15,Petal.Width,Sepal.Length,0.383911,regression,mean absolute error,DecisionTreeRegressor()
16,Petal.Width,Sepal.Width,0.254616,regression,mean absolute error,DecisionTreeRegressor()
21,Species,Sepal.Width,0.194307,regression,mean absolute error,DecisionTreeRegressor()
7,Sepal.Width,Petal.Length,0.172375,regression,mean absolute error,DecisionTreeRegressor()
9,Sepal.Width,Species,0.156915,classification,weighted F1,DecisionTreeClassifier()
8,Sepal.Width,Petal.Width,0.132858,regression,mean absolute error,DecisionTreeRegressor()
11,Petal.Length,Sepal.Width,0.052136,regression,mean absolute error,DecisionTreeRegressor()
5,Sepal.Width,Sepal.Length,0.006966,regression,mean absolute error,DecisionTreeRegressor()
1,Sepal.Length,Sepal.Width,0.000000,regression,mean absolute error,DecisionTreeRegressor()